
# **Assignment - 1 : Getting Started**

---

This assignment will get you familiarized with python libraries required for ***data science*** and ***machine learning***. You will have to complete the code snippets and run them. 

## **Note :**   Use only the methods and attributes of the ```numpy``` library. **Do not** hard-code them. Avoid loops as much as possible.

---
## Part - 1
 In this part, you will work with the library ```numpy```. 




Import ```numpy``` with an alias name ```np```. Initialize two arrays $a$, $b$ of size $3 \times 5$ with random values and print them. 

In [1]:
import numpy as np
a = np.random.randn(3,5)
b = np.random.randn(3,5)
print(a)
print(b)

[[ 0.44402733 -0.51881681 -0.07302881  1.28401493 -0.30413911]
 [ 1.00107763 -0.68088041 -0.65759994  1.42367484 -1.82227282]
 [-1.37636979  0.723559   -0.04245715 -0.64159496  0.17599857]]
[[-1.72708228  1.07330315  0.69194651  0.16843777  0.38286313]
 [ 0.11429363 -0.23458543  1.02350345 -0.04035507 -1.31632305]
 [ 0.51389232  0.7197978   1.4545071  -0.73545226 -0.49340616]]


Initialize and print two arrays $c$ and $d$ having the following properties:
*   $c$ is a row vector with all non-negative integer values less than 100
* $d$ is a square matrix of size 3 having all entries as 0.0

In [4]:

c = np.arange(0,100).reshape(100)
d = np.zeros((3,3))
print(c)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


We have $e$ as following : ```e = [[1,2,3],[4,5,6],[7,8,9]]```. Change $e$ as a numpy array and print it.

In [0]:
e = [[1,2,3],[4,5,6],[7,8,9]]
e = np.array(e)
print(e)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


$f$ and $g$ are two square matrices of size 5 such that all the entries of $f$ are 1 and $g$ is an identity matrix. Initialize them and print them

In [0]:
f = np.ones((5,5))
print(f)
g = np.identity(5)
print(g)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Reshape $c$ into a $10 \times 10$ matrix and name it $h$. Now flatten $h$, call it $c^\prime$ and print **YES** when the shapes of $c$ and $c^\prime$ are same. Otherwise print **NO**.

In [9]:
h = c.reshape(10,10)
print(h)
c_t = h.flatten()
print(c_t)

if c.shape == c_t.shape :
  print('YES')
else:
  print('NO')

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
YES


Let $A$ denote a randomly initialized three dimensional matrix of shape (2,10,5). Transpose $A$, call it $A^\prime$, such that its shape is (5,2,10) and print it.

In [0]:
A = np.random.rand(2,10,5)
A_t = A.transpose(2,0,1)
A_t



array([[[0.53958012, 0.11383069, 0.50916849, 0.84601042, 0.91156891,
         0.15138072, 0.83634654, 0.19514397, 0.04769852, 0.93713909],
        [0.25633593, 0.43805615, 0.0154227 , 0.88941471, 0.75190614,
         0.6789183 , 0.76811148, 0.42654565, 0.83420945, 0.25185487]],

       [[0.78122501, 0.98954243, 0.00889735, 0.3124098 , 0.4001578 ,
         0.27823413, 0.7484886 , 0.01133079, 0.96108359, 0.38132012],
        [0.65404141, 0.77811621, 0.88965243, 0.34313309, 0.07681071,
         0.52947313, 0.56205214, 0.43339238, 0.40869801, 0.85637797]],

       [[0.24563241, 0.67092552, 0.76613001, 0.74623344, 0.69442735,
         0.0380409 , 0.80463631, 0.99934668, 0.88514469, 0.24795391],
        [0.64673453, 0.96017769, 0.63403565, 0.47777242, 0.59858782,
         0.94908549, 0.13666176, 0.54961812, 0.74534003, 0.43391373]],

       [[0.75102281, 0.17493748, 0.78371816, 0.1447338 , 0.30218928,
         0.99403468, 0.20467463, 0.58577056, 0.66666126, 0.73193799],
        [0.48175748, 

You have a matrix $X$ of size (10,5) filled with random values. Print the following :
* Minimum value and index where it occured, for each column
* Maximum value and the index where it occured, for each column
* Minimum value and index where it occured, for each row
* Maximum value and index where it occured, for each row
* Minimum value and index where it occured, for the entire matrix
* Maximum value and index where it occured, for the entire matrix

In [0]:
np.random.seed(0)
X = np.random.rand(10,5)
print(X)

#Minimum value and index where it occured, for each column
print(X.min(0))
print(X.argmin(0))

#Maximum value and the index where it occured, for each column
print(X.max(0))
print(X.argmax(0))
#Minimum value and index where it occured, for each row

print(X.min(1))
print(X.argmin(1))
#Maximum value and index where it occured, for each row

print(X.max(1))
print(X.argmax(1))

#Minimum value and index where it occured, for the entire matrix

print(X.min())
print(X.argmin())

#Maximum value and index where it occured, for the entire matrix
print(X.max())
print(X.argmax())






[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]
 [0.63992102 0.14335329 0.94466892 0.52184832 0.41466194]
 [0.26455561 0.77423369 0.45615033 0.56843395 0.0187898 ]
 [0.6176355  0.61209572 0.616934   0.94374808 0.6818203 ]
 [0.3595079  0.43703195 0.6976312  0.06022547 0.66676672]
 [0.67063787 0.21038256 0.1289263  0.31542835 0.36371077]]
[0.0871293  0.0202184  0.1289263  0.06022547 0.0187898 ]
[3 3 9 8 6]
[0.97861834 0.79915856 0.94466892 0.96366276 0.87001215]
[4 4 5 1 3]
[0.4236548  0.38344152 0.07103606 0.0202184  0.11827443 0.14335329
 0.0187898  0.61209572 0.06022547 0.1289263 ]
[4 4 4 1 4 1 4 1 3 2]
[0.71518937 0.96366276 0.92559664 0.87001215 0.97861834 0.94466892
 0.77423369 0.94374808 0.6976312  0.67063787]
[1 3 3 4 0 2 1 3 2 0]
0.018789800

Find and print the following for the matrix X: 
* Mean of each row and column
* Standard deviation of each row and column
* Mean of the entire matrix
* Standard deviation of entire matrix

In [0]:
#Mean of each row and column
print(X.mean(0))
print(X.mean(1))

#Standard deviation of each row and column
print(X.std(0))
print(X.std(1))

#Mean of the entire matrix
print(X.mean())
#Standard deviation of entire matrix
print(X.std())


[0.56044382 0.46781457 0.62009909 0.64025127 0.40121685]
[0.56706085 0.66447172 0.57705944 0.51762729 0.62761197 0.5328907
 0.41643268 0.69444672 0.44423265 0.33781717]
[0.24687647 0.25752158 0.22948615 0.28054144 0.26584905]
[0.09445299 0.23322986 0.29189733 0.38052993 0.30431633 0.26338419
 0.25841437 0.12727959 0.23169975 0.18537332]
0.5379651182755409
0.27226582292177587


Let $Y$ denote a square matrix of size 10 with random values. Print the following:
* Determinant
* Rank of the matrix
* Diagonal Elements
* Trace
* Eigen values
* Matrices obtained after Singular Value Decomposition
* Inverse if exists, otherwise Pseudo-Inverse
* Multiplication $Y$ with $X$
* Element-wise multiplication of $Y$ and its inverse(or pseudo-inverse)

In [0]:
np.random.seed(3)
Y = np.random.rand(10,10)

#Determinant
print()
#Rank of the matrix

#Diagonal Elements
#Trace
#Eigen values
#Matrices obtained after Singular Value Decomposition
#Inverse if exists, otherwise Pseudo-Inverse
#Multiplication  Y  with  X 
#Element-wise multiplication of  Y  and its inverse(or pseudo-inverse)




In [0]:
np.random.seed(3)
Y = np.random.rand(10,10)

#Determinant
print('The determinant of the matrix is:')
print(np.linalg.det(Y))

#Rank of the matrix
print('The rank of the matrix is:')
print(np.linalg.matrix_rank(Y))

#Diagonal Elements
print('The trace of the Diagonal Elements of the matrix are:')
print(np.diagonal(Y))

#Trace
print('The trace of the matrix is:')
print(np.trace(Y))

#Eigen values
print('The eigen value of the matrix is:')
print(np.linalg.eig(Y))

#Matrices obtained after Singular Value Decomposition
print('The SVD matrix of the matrix is:')
print(np.linalg.svd(Y))

#Inverse if exists, otherwise Pseudo-Inverse
Y_inv = np.linalg.pinv(Y)
print('The inverse of the matrix is:')
print(Y_inv)

#Multiplication  Y  with  X 
print('multiplicatiob result of X and Y = :')
print(np.matmul(Y,X))

#Element-wise multiplication of  Y  and its inverse(or pseudo-inverse)
print('Element-wise multiplication of  Y  and its inverse:')
print(np.multiply(Y, Y_inv))




The determinant of the matrix is:
-0.012807808169095483
The rank of the matrix is:
10
The trace of the Diagonal Elements of the matrix are:
[0.5507979  0.45683322 0.44045372 0.84575087 0.4576864  0.36217621
 0.06152893 0.19897603 0.92672568 0.19638058]
The trace of the matrix is:
4.497309545724899
The eigen value of the matrix is:
(array([ 4.797525  +0.j        ,  0.72411408+0.52238181j,
        0.72411408-0.52238181j, -0.48250062+0.55413671j,
       -0.48250062-0.55413671j, -0.6909002 +0.j        ,
       -0.25905659+0.32357377j, -0.25905659-0.32357377j,
        0.2127855 +0.08352477j,  0.2127855 -0.08352477j]), array([[ 0.29593906+0.j        ,  0.14213977+0.19798456j,
         0.14213977-0.19798456j, -0.37236549+0.00325385j,
        -0.37236549-0.00325385j, -0.1096481 +0.j        ,
        -0.0132423 +0.12273111j, -0.0132423 -0.12273111j,
        -0.56228934-0.10973258j, -0.56228934+0.10973258j],
       [ 0.25059285+0.j        ,  0.01404552+0.1967944j ,
         0.01404552-0.1967944j

## End of Part - 1
 --- --- ---

## Part - 2
---
In this part, you will be working with the library ```pandas```. Import this library with an alias name ```pd```.

In [0]:
# Initial imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv
Read the data and display the first 5 rows

In [5]:
#Download dataset from: http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv

file_url = "http://biostat.mc.vanderbilt.edu/wiki/pub/Main/DataSets/titanic3.csv"

df = pd.read_csv(file_url)
df.head()

pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

### Preprocessing of the Dataset



---


**1. Convert the categorical values of columns 'sex', 'embarked', 'pclass' into dummy values and add them into titanic_data_new DataFrame**




---



In [6]:
dummies = []
cols = ['pclass', 'sex', 'embarked']
for col in cols:
    dummies.append(pd.get_dummies(df[col]))
titanic_data_new = pd.concat(dummies, axis=1)
titanic_data_new.head()


1  2  3  female  male  C  Q  S
0  1  0  0       1     0  0  0  1
1  1  0  0       0     1  0  0  1
2  1  0  0       1     0  0  0  1
3  1  0  0       0     1  0  0  1
4  1  0  0       1     0  0  0  1



---


**2. Fill the missing data in Age and Fare columns with the mean value of the respected column then add these columns to titanic_data_new**


---



In [7]:
 df.head()
 

pclass  survived  ...   body                        home.dest
0       1         1  ...    NaN                     St Louis, MO
1       1         1  ...    NaN  Montreal, PQ / Chesterville, ON
2       1         0  ...    NaN  Montreal, PQ / Chesterville, ON
3       1         0  ...  135.0  Montreal, PQ / Chesterville, ON
4       1         0  ...    NaN  Montreal, PQ / Chesterville, ON

[5 rows x 14 columns]

In [8]:
age_mean = df["age"].mean()
print(age_mean)
fare_mean = df["fare"].mean()
print(age_mean)

age = df["age"].fillna(value = age_mean)
fare = df["fare"].fillna(value = fare_mean)
titanic_data_new = pd.concat([titanic_data_new, age, fare], axis = 1)
print (titanic_data_new)




29.881137667304014
29.881137667304014
      1  2  3  female  male  C  Q  S        age      fare
0     1  0  0       1     0  0  0  1  29.000000  211.3375
1     1  0  0       0     1  0  0  1   0.920000  151.5500
2     1  0  0       1     0  0  0  1   2.000000  151.5500
3     1  0  0       0     1  0  0  1  30.000000  151.5500
4     1  0  0       1     0  0  0  1  25.000000  151.5500
...  .. .. ..     ...   ... .. .. ..        ...       ...
1304  0  0  1       1     0  1  0  0  14.500000   14.4542
1305  0  0  1       1     0  1  0  0  29.881138   14.4542
1306  0  0  1       0     1  1  0  0  26.500000    7.2250
1307  0  0  1       0     1  1  0  0  27.000000    7.2250
1308  0  0  1       0     1  0  0  1  29.000000    7.8750

[1309 rows x 10 columns]


###Normalization


---



1. Normalize the columns which have numerical data



---



In [10]:
titanic_data_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   1       1309 non-null   uint8  
 1   2       1309 non-null   uint8  
 2   3       1309 non-null   uint8  
 3   female  1309 non-null   uint8  
 4   male    1309 non-null   uint8  
 5   C       1309 non-null   uint8  
 6   Q       1309 non-null   uint8  
 7   S       1309 non-null   uint8  
 8   age     1309 non-null   float64
 9   fare    1309 non-null   float64
dtypes: float64(2), uint8(8)
memory usage: 30.8 KB


In [0]:
age = (age - age.mean())/age.std()
fare = (fare - fare.mean())/fare.std()
columns = df.select_dtypes(include=['int','float'])


In [14]:
print(titanic_data_new)

      1  2  3  female  male  C  Q  S        age      fare
0     1  0  0       1     0  0  0  1  29.000000  211.3375
1     1  0  0       0     1  0  0  1   0.920000  151.5500
2     1  0  0       1     0  0  0  1   2.000000  151.5500
3     1  0  0       0     1  0  0  1  30.000000  151.5500
4     1  0  0       1     0  0  0  1  25.000000  151.5500
...  .. .. ..     ...   ... .. .. ..        ...       ...
1304  0  0  1       1     0  1  0  0  14.500000   14.4542
1305  0  0  1       1     0  1  0  0  29.881138   14.4542
1306  0  0  1       0     1  1  0  0  26.500000    7.2250
1307  0  0  1       0     1  1  0  0  27.000000    7.2250
1308  0  0  1       0     1  0  0  1  29.000000    7.8750

[1309 rows x 10 columns]




---
2. Drop the original age, fare columns
3. Append the normalized columns to the titanic_data_new DataFrame.



---



In [17]:
titanic_data_new = titanic_data_new.drop(columns = ['age', 'fare'])
titanic_data_new = pd.concat([titanic_data_new,age,fare], axis =1)
print(titanic_data_new)

      1  2  3  female  male  C  Q  S           age      fare
0     1  0  0       1     0  0  0  1 -6.839435e-02  3.441165
1     1  0  0       0     1  0  0  1 -2.247978e+00  2.285603
2     1  0  0       1     0  0  0  1 -2.164148e+00  2.285603
3     1  0  0       0     1  0  0  1  9.226155e-03  2.285603
4     1  0  0       1     0  0  0  1 -3.788764e-01  2.285603
...  .. .. ..     ...   ... .. .. ..           ...       ...
1304  0  0  1       1     0  1  0  0 -1.193892e+00 -0.364161
1305  0  0  1       1     0  1  0  0  1.436174e-16 -0.364161
1306  0  0  1       0     1  1  0  0 -2.624456e-01 -0.503886
1307  0  0  1       0     1  1  0  0 -2.236354e-01 -0.503886
1308  0  0  1       0     1  0  0  1 -6.839435e-02 -0.491323

[1309 rows x 10 columns]


###Plotting
1. plot the age against the ID(continuous)
2. plot the fare against the ID(scatter)

In [0]:
titanic_data_new['age'].plot(kind='line')
plt.show()
titanic_data_new.plot(kind='scatter',x='index',y='fare')
plt.show()

## End of Part - 2
---

## Part - 3
---

In this part, you will work with the library ```matplotlib```. Import the ```pyplot``` from ```matplotlib``` with an alias name ```plt```.

In [0]:
from matplotlib import pyplot as plt

Plot the sine function with domain in $[-3\pi,3\pi]$. Label the axes appropriately. Add title $\sin(x)$. Use latex formatting while adding the title. Set the plot size to (10,10)

In [0]:
x = np.linspace(-3*np.pi,3*np.pi,300)
y = np.sin(x)
plt.figure(figsize=(10,10))
plt.plot(x,y)
plt.title(r'$\sin(x)$')
plt.show()

Plot $\sin(x)$ and its spectrum, $\cos(x)$ and its spectrum in a single plot, in the domain $[-2\pi,2\pi]$. Label the plot appropriately.

In [0]:
X = np.linspace(-2*np.pi,2*np.pi,200)
sin = np.sin(X)
cos = np.cos(X)
Sin = np.fft.fft(sin)
Cos = np.fft.fft(cos)
freq = np.fft.fftfreq(X.shape[-1])
plt.figure(1,figsize=(10,10))
plt.subplot(1,2,1)
plt.plot(X,sin)
plt.title(r'$\sin(x)$')
plt.xlabel('x')
plt.subplot(1,2,2)
plt.plot(freq,Sin)
plt.title('Fourier Transform')
plt.xlabel('freq')
plt.show()
plt.figure(2,figsize=(10,10))
plt.subplot(1,2,1)
plt.plot(X,cos)
plt.title(r'$\cos(x)$')
plt.xlabel('x')
plt.subplot(1,2,2)
plt.plot(freq,Cos)
plt.title('Fourier Transform')
plt.xlabel('freq')
plt.show()

## End of Part - 3
---

Create a Github repository with the name ***SHALA2020*** and save this assignment there.